server:
  port: 6688

spring:
  mail:
    # 邮件服务地址
    host: smtp.163.com
    # 端口,可不写默认
    port: 25
    # 编码格式
    default-encoding: utf-8
    # 用户名
    username: mpanxue@163.com
    # 授权码，就是我们刚才准备工作获取的代码
    password: FFLEMZESFNNMPOVG
    # 其它参数
    properties:
      mail:
        smtp:
        ssl:
        enable: true
        required: true
        # 邮件接收时间的限制，单位毫秒
        timeout: 10000
        # 连接时间的限制，单位毫秒
        connectiontimeout: 10000
        # 邮件发送时间的限制，单位毫秒
        writetimeout: 10000